### ISSUE TITLE
Failed to activate the org package

### ISSUE THREAD

**Issue by sean-sh** [wolfgang/org#11]
Right after pressing ctrl-alt-o for the first time

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [org](https://github.com/wolfgang/org) package, v0.2.5

### Stack Trace

Failed to activate the org package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
  at new OrgInput (/Users/sean/.atom/packages/org/lib/org-input.coffee:9:23)
  at Object.module.exports.activate (/Users/sean/.atom/packages/org/lib/org.coffee:5:17)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -2:03.7.0 core:cancel (a.)
  2x -1:29 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:32.2.0 application:open (ul.list-inline.tab-bar.inset-panel)
     -0:25.8.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -0:21.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:19.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:01.3.0 org:toggle (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.6
emacs, v0.7.2
linter, v0.12.6
omnisharp-atom, v0.12.0
org, v0.2.5

# Dev
No dev packages
```

**Comment by jerryling315** [comment]
any followups?

**Comment by reverland** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Ubuntu 14.04.3
**Thrown From**: [org](https://github.com/wolfgang/org) package, v0.2.5


### Stack Trace

Failed to activate the org package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
    at new OrgInput (/home/reverland/.atom/packages/org/lib/org-input.coffee:9:23)
    at Object.module.exports.activate (/home/reverland/.atom/packages/org/lib/org.coffee:5:17)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:170:19)
    at /usr/share/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:512:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:490:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:474:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:668:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:40:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:51:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:79:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
color-picker, v2.0.13
devdocs, v0.2.1
emmet, v2.3.14
markdown-preview-plus, v2.2.2
org, v0.2.5
pigments, v0.18.1
terminal-plus, v0.14.3
vim-mode, v0.63.0

# Dev
No dev packages
```

Yup!
